# Generated by Django 5.2.1 on 2025-06-26 12:31

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0004_student_remove_attendancerecord_person_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendancerecord',
            options={'ordering': ['-timestamp']},
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='is_late',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='source',
            field=models.CharField(choices=[('auto', 'Auto Face Recognition'), ('manual', 'Manual Marking'), ('override', 'Developer Override')], default='auto', max_length=20),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='source_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recognition.event'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_entries', to='recognition.student'),
        ),
        migrations.AlterField(
            model_name='attendancerecord',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student')},
        ),
    ]
