# Generated by Django 5.2.1 on 2025-08-21 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0011_alter_attendancerecord_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidentifiedface',
            name='image_path',
        ),
        migrations.AddField(
            model_name='unidentifiedface',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/unidentified/'),
        ),
    ]
