# Generated by Django 5.2.1 on 2025-08-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0012_remove_unidentifiedface_image_path_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedface',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
