# Generated by Django 5.2.1 on 2025-08-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0013_unidentifiedface_image_path'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidentifiedface',
            name='image_path',
        ),
        migrations.AlterField(
            model_name='unidentifiedface',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='unidentified/'),
        ),
    ]
