# Generated by Django 5.2.1 on 2025-08-21 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0014_remove_unidentifiedface_image_path_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unidentifiedface',
            name='image',
        ),
        migrations.AddField(
            model_name='unidentifiedface',
            name='cropped_face',
            field=models.ImageField(blank=True, null=True, upload_to='unidentified/cropped/'),
        ),
        migrations.AddField(
            model_name='unidentifiedface',
            name='full_frame',
            field=models.ImageField(blank=True, null=True, upload_to='unidentified/full/'),
        ),
    ]
