# Generated by Django 5.2.1 on 2025-08-22 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0015_remove_unidentifiedface_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unidentifiedface',
            name='detected_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='unidentifiedface',
            name='encoding',
            field=models.BinaryField(blank=True, null=True),
        ),
    ]
