# Generated by Django 5.2.1 on 2025-06-26 09:53

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0003_session_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=100)),
                ('registration_number', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, unique=True)),
                ('course', models.CharField(blank=True, max_length=100)),
                ('year_of_study', models.PositiveIntegerField(default=1)),
                ('face_encoding_path', models.CharField(blank=True, help_text='Path to saced face encoding file if used.', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='attendancerecord',
            name='person',
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='session',
            field=models.ForeignKey(default='ccd64155-4f5e-447e-89ae-d68a3e7bc6b6', on_delete=django.db.models.deletion.CASCADE, related_name='attendance_records', to='recognition.session'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='source_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_records', to='recognition.event'),
        ),
        migrations.AddField(
            model_name='attendancerecord',
            name='student',
            field=models.ForeignKey(default='ccd64155-4f5e-447e-89ae-d68a3e7bc6b6', on_delete=django.db.models.deletion.CASCADE, to='recognition.student'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Person',
        ),
    ]
