# Generated by Django 5.2.1 on 2025-07-11 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0007_classgroup_session_class_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='UnidentifiedFace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_path', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unidentified_faces', to='recognition.session')),
            ],
        ),
    ]
