# Generated by Django 5.2.1 on 2025-07-17 16:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0008_unidentifiedface'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='recognition.student'),
        ),
    ]
