# Generated by Django 5.2.1 on 2025-07-24 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0009_event_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='severity',
            field=models.CharField(choices=[('info', 'Info'), ('warning', 'Warning'), ('error', 'Error'), ('critical', 'Critical')], default='info', max_length=10),
        ),
    ]
