# Generated by Django 5.2.1 on 2025-08-02 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recognition', '0010_event_severity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='attendancerecord',
            unique_together={('session', 'student')},
        ),
    ]
